### ISSUE TITLE
Cannot access to /search/message in en/ko.

### ISSUE THREAD

**Issue by hwahyang1** [outloudvi/info-pride#104]
![image](https://github.com/outloudvi/info-pride/assets/40535405/0c43b545-c437-44de-a1b1-10c2fc82c699)

**Comment by outloudvi** [comment]
Thanks for the report! It seems to be related to some change at our bacakend MongoDB side. The edge case has now been handled by MalitsPlus/IDOLY-Backend@fa30eb2f80f936a1aa2c64ac5d742add5e15d7d8.
