### ISSUE TITLE
Width issue when exporting picture from MacaronTalk

### ISSUE THREAD

**Issue by Marxel-cn** [outloudvi/info-pride#42]
Sample talk contents:
`[
  {
    "characterId": "char-mhk",
    "text": "─miho发送了文件─"
  },
  {
    "characterId": "char-mhk",
    "text": "是关于对战的对手「恋々Poison」的资料哦。我已经调查\n了很多方面，不过就三局两胜的比赛内容来说，这次也\n是要先准备对策比较好哦"
  },
  {
    "characterId": "char-mhk",
    "text": "从准备跟fran进行自己更拿手的游泳比赛上来看，对方也\n调查了我们很多呢"
  },
  {
    "characterId": "char-kor",
    "text": "对方这履历，感觉有点作弊级了"
  },
  {
    "characterId": "char-kan",
    "text": "27页之后的内容是不是风格全变了？"
  },
  {
    "characterId": "char-kan",
    "text": "连恋Poi的小道消息都收集了笑死w"
  }
]`

Preview in browser:
![image](https://github.com/outloudvi/info-pride/assets/69199776/a7d2aa95-3685-49c1-9ae1-7ed0f742be5c)

Exported image:
![image](https://github.com/outloudvi/info-pride/assets/69199776/409bd254-7aab-43f3-90d5-71d7b70fc1c5)

**Comment by outloudvi** [comment]
已经复现，感谢报告。

我得看看是不是 [satori](https://www.npmjs.com/package/satori) 的渲染出问题了……

**Comment by outloudvi** [comment]
图片导出时文字出界的问题应该有解决。
借此也调整了一下渲染区域的格式，目前可能和 IP 游戏内的样式不是很像。这个问题会在 #46 跟踪。
