### ISSUE TITLE
Question: About translation contributions

### ISSUE THREAD

**Issue by hwahyang1** [outloudvi/info-pride#63]
hello! Can I participate in the Korean translation?
If possible, how should I proceed?

**Comment by outloudvi** [comment]
Hi! Translation helps are appreciated, but please note that info-pride currently only contains contents from the Japanese service run by QualiArts, not contents from the Global service run by NEOWIZ.

If you are interested, I can create a scaffold for Korean in one day or two, after which translations can be contributed via PRs over GitHub or (probably more conveniently for contributors) [our Transifex project](https://app.transifex.com/info-pride/). I'll let you know when it's ready.

**Comment by hwahyang1** [comment]
I understand. I would like to participate in the project.

**Comment by outloudvi** [comment]
Thanks a lot! I'll let you know when the scaffolding is ready for accepting translations.

**Comment by outloudvi** [comment]
Hi. Now that Korean shall have been added to the project code as well as the Transifex project. Based on their preference, translators may PR directly or use [the Transifex website](https://app.transifex.com/info-pride/) to submit translations. For Transifex cases, once the translation rate reaches 50%, a PR should be created by Transifex to merge them.
Contributing in whichever way, translators are welcomed to request themselves into the contributor list by asking in #1 if they wish (primarily for Transfiex users, for PRs I'll do it automatically).
